In [29]:
import  nltk

In [30]:
nltk.download("wordnet")
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('omw-1.4')
from nltk.corpus import stopwords

stopwords.words('arabic')

[nltk_data] Downloading package wordnet to /home/dominik/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /home/dominik/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/dominik/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to /home/dominik/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


['إذ',
 'إذا',
 'إذما',
 'إذن',
 'أف',
 'أقل',
 'أكثر',
 'ألا',
 'إلا',
 'التي',
 'الذي',
 'الذين',
 'اللاتي',
 'اللائي',
 'اللتان',
 'اللتيا',
 'اللتين',
 'اللذان',
 'اللذين',
 'اللواتي',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'أم',
 'أما',
 'أما',
 'إما',
 'أن',
 'إن',
 'إنا',
 'أنا',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'إنما',
 'إنه',
 'أنى',
 'أنى',
 'آه',
 'آها',
 'أو',
 'أولاء',
 'أولئك',
 'أوه',
 'آي',
 'أي',
 'أيها',
 'إي',
 'أين',
 'أين',
 'أينما',
 'إيه',
 'بخ',
 'بس',
 'بعد',
 'بعض',
 'بك',
 'بكم',
 'بكم',
 'بكما',
 'بكن',
 'بل',
 'بلى',
 'بما',
 'بماذا',
 'بمن',
 'بنا',
 'به',
 'بها',
 'بهم',
 'بهما',
 'بهن',
 'بي',
 'بين',
 'بيد',
 'تلك',
 'تلكم',
 'تلكما',
 'ته',
 'تي',
 'تين',
 'تينك',
 'ثم',
 'ثمة',
 'حاشا',
 'حبذا',
 'حتى',
 'حيث',
 'حيثما',
 'حين',
 'خلا',
 'دون',
 'ذا',
 'ذات',
 'ذاك',
 'ذان',
 'ذانك',
 'ذلك',
 'ذلكم',
 'ذلكما',
 'ذلكن',
 'ذه',
 'ذو',
 'ذوا',
 'ذواتا',
 'ذواتي',
 'ذي',
 'ذين',
 'ذينك',
 'ريث',
 'سوف',
 'سوى',
 'شتان',
 'عدا',
 'عسى',
 'عل'

In [36]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

import nltk
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.corpus import wordnet

def get_wordnet_pos(treebank_tag):
  if treebank_tag.startswith('J'):
    return wordnet.ADJ
  elif treebank_tag.startswith('V'):
    return wordnet.VERB
  elif treebank_tag.startswith('N'):
    return wordnet.NOUN
  elif treebank_tag.startswith('R'):
    return wordnet.ADV
  else:
    return wordnet.NOUN

class LemmaTokenizer:
  def __init__(self):
    self.wnl = WordNetLemmatizer()
  def __call__(self, doc):
    tokens = word_tokenize(doc)
    words_and_tags = nltk.pos_tag(tokens)
    return [self.wnl.lemmatize(word, pos=get_wordnet_pos(tag)) \
            for word, tag in words_and_tags]

In [46]:
s = ["She likes me.", 'She was walking with me She walked bitch']
l = LemmaTokenizer()
print(l(s[0]))
print(l(s[1]))

['She', 'like', 'me', '.']
['She', 'be', 'walk', 'with', 'me', 'She', 'walk', 'bitch']


In [49]:
vectorizer = CountVectorizer(tokenizer=LemmaTokenizer())
Xtrain = vectorizer.fit_transform(s)
Xtrain.toarray()
vectorizer.get_feature_names()

/home/dominik/anaconda3/envs/dominiktomalczyk/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['.', 'be', 'bitch', 'like', 'me', 'she', 'walk', 'with']

In [52]:
c = LemmaTokenizer()
c(s[0])

['She', 'like', 'me', '.']

In [7]:
cols

array([4, 2, 3, 4, 3, 0, 5, 6, 1], dtype=int32)

In [8]:
Xtrain.toarray()

array([[0, 0, 1, 1, 1, 0, 0],
       [1, 1, 0, 1, 2, 2, 1]])

In [9]:
sentence = "The following is stupid".split()
sentence2 = "cat was following the dog".split()

In [10]:
print(nltk.pos_tag(sentence))

[('The', 'DT'), ('following', 'NN'), ('is', 'VBZ'), ('stupid', 'JJ')]


In [11]:
print(nltk.pos_tag(sentence2))

[('cat', 'NN'), ('was', 'VBD'), ('following', 'VBG'), ('the', 'DT'), ('dog', 'NN')]


In [12]:
vectorizer = CountVectorizer(tokenizer=LemmaTokenizer())
Xtrain = vectorizer.fit_transform(s)
Xtrain.toarray()

array([[0, 0, 1, 1, 1, 0, 0],
       [1, 1, 0, 1, 2, 2, 1]])

In [13]:
vectorizer = CountVectorizer(tokenizer=LemmaTokenizer(), stop_words=["she"])
Xtrain = vectorizer.fit_transform(s)
Xtrain.toarray()

array([[0, 0, 1, 1, 0, 0],
       [1, 1, 0, 1, 2, 1]])

In [14]:
import spacy

ModuleNotFoundError: No module named 'spacy'

In [15]:
v = np.array([1,2,3])
v2 = v/np.linalg.norm(v)

In [16]:
np.linalg.norm(v)

3.7416573867739413

In [16]:
from sklearn.preprocessing import normalize
v1 = np.array([1,2])
v2 = np.array([3,7])
v3 = np.array([7,8])

v1 = normalize(v1.reshape(1, -1))
v2 = normalize(v2.reshape(1, -1))
v3 = normalize(v3.reshape(1, -1))

In [17]:

from sklearn.metrics.pairwise import cosine_distances, euclidean_distances
from sklearn.preprocessing import normalize
print(cosine_distances(v1.reshape(1,-1),v2.reshape(1, -1)))
print((euclidean_distances(v1.reshape(1,-1),v2.reshape(1, -1))))

print(cosine_distances(v1.reshape(1,-1),v3.reshape(1, -1)))
print(euclidean_distances(v1.reshape(1,-1),v3.reshape(1, -1)))

[[0.00172563]]
[[0.05874737]]
[[0.03238273]]
[[0.25449058]]


In [18]:
0.03238273 / 0.00172563

18.765743525552985

In [19]:
(0.25449058 / 0.05874737)**2


18.76577760749242

In [20]:
v1 = np.array([1,2,3])

v1 = normalize(v1.reshape(1, -1))
v1

array([[0.26726124, 0.53452248, 0.80178373]])

In [21]:
np.linalg.norm(v1)

1.0

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
   'And this is the documents third one.',
    'Is this the first document?',
]
vectorizer = TfidfVectorizer(tokenizer=LemmaTokenizer())
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()
X.toarray()

array([[0.43855558, 0.        , 0.        , 0.35854792, 0.35854792,
        0.54170339, 0.        , 0.        , 0.35854792, 0.        ,
        0.35854792],
       [0.35064154, 0.        , 0.        , 0.28667243, 0.57334487,
        0.        , 0.        , 0.54934773, 0.28667243, 0.        ,
        0.28667243],
       [0.30100231, 0.        , 0.47157828, 0.24608911, 0.24608911,
        0.        , 0.47157828, 0.        , 0.24608911, 0.47157828,
        0.24608911],
       [0.        , 0.60735961, 0.        , 0.31694544, 0.31694544,
        0.4788493 , 0.        , 0.        , 0.31694544, 0.        ,
        0.31694544]])

In [26]:
vectorizer.get_feature_names_out()

array(['.', '?', 'and', 'be', 'document', 'first', 'one', 'second', 'the',
       'third', 'this'], dtype=object)

In [27]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()
X.toarray()

array([[0.        , 0.46979139, 0.        , 0.58028582, 0.38408524,
        0.        , 0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.        , 0.28108867,
        0.        , 0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.45563143, 0.        , 0.45563143, 0.        , 0.23776738,
        0.45563143, 0.        , 0.23776738, 0.45563143, 0.23776738],
       [0.        , 0.46979139, 0.        , 0.58028582, 0.38408524,
        0.        , 0.        , 0.38408524, 0.        , 0.38408524]])

In [28]:
vectorizer.get_feature_names_out()

array(['and', 'document', 'documents', 'first', 'is', 'one', 'second',
       'the', 'third', 'this'], dtype=object)

In [135]:
X[1].toarray()

array([[0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867]])

In [150]:
y = ['apple black cook black black black', 'cook delay eagle', 'delay eagle fuck']
vectorizer = CountVectorizer(max_features=2)
ou = vectorizer.fit_transform(y)
print(ou)

  (0, 0)	4
  (0, 1)	1
  (1, 1)	1


In [151]:
ou.toarray()

array([[4, 1],
       [0, 1],
       [0, 0]])

In [152]:
vectorizer.get_feature_names()

/home/dominik/anaconda3/envs/dominiktomalczyk/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['black', 'cook']

In [153]:
# https://www.kaggle.com/shivamkushwaha/bbc-full-text-document-classification
!wget -nc https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv

--2023-05-05 22:35:29--  https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv
Resolving lazyprogrammer.me (lazyprogrammer.me)... 104.21.23.210, 172.67.213.166, 2606:4700:3030::ac43:d5a6, ...
Connecting to lazyprogrammer.me (lazyprogrammer.me)|104.21.23.210|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5085081 (4.8M) [text/csv]
Saving to: ‘bbc_text_cls.csv’

bbc_text_cls.csv    100%[===================>]   4.85M  1.71MB/s    in 2.8s    

2023-05-05 22:35:33 (1.71 MB/s) - ‘bbc_text_cls.csv’ saved [5085081/5085081]



In [45]:
import pandas as pd
import numpy as np
import nltk

from nltk import word_tokenize
nltk.download('punkt')
df = pd.read_csv('bbc_text_cls.csv')
# populate word2idx
# convert documents into sequences of ints / ids / indices
idx = 0
word2idx = {}
tokenized_docs = []
for doc in df['text']:
  words = word_tokenize(doc.lower())
  doc_as_int = []
  for word in words:
    if word not in word2idx:
      word2idx[word] = idx
      idx += 1

    # save for later
    doc_as_int.append(word2idx[word])
  tokenized_docs.append(doc_as_int)
# reverse mapping
# if you do it smarter you can store it as a list
idx2word = {v:k for k, v in word2idx.items()}
# number of documents
N = len(df['text'])

[nltk_data] Downloading package punkt to /home/dominik/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [46]:
N

2225

In [47]:
# number of words
V = len(word2idx)
V

34762

In [48]:
# instantiate term-frequency matrix
# note: could have also used count vectorizer
tf = np.zeros((N, V))
# populate term-frequency counts
for i, doc_as_int in enumerate(tokenized_docs):
  for j in doc_as_int:
    tf[i, j] += 1

tf

array([[1., 4., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.]])

In [49]:
tf > 0

array([[ True,  True,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True]])

In [50]:

# compute IDF
document_freq = np.sum(tf > 0, axis=0)
document_freq

array([ 12, 204, 127, ...,   1,   1,   1])

In [51]:

# document frequency (shape = (V,))
idf = np.log(N / document_freq)
idf

array([5.22260554, 2.3893922 , 2.86332511, ..., 7.70751219, 7.70751219,
       7.70751219])

In [52]:
# compute TF-IDF
tf_idf = tf * idf
tf_idf

array([[5.22260554, 9.5575688 , 2.86332511, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 2.86332511, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 7.70751219, 7.70751219,
        7.70751219]])

In [53]:
np.random.seed(123)
# pick a random document, show the top 5 terms (in terms of tf_idf score)
i = np.random.choice(N)
i

1346

In [64]:

i = 15

row = df.iloc[i]
print("Label:", row['labels'])
print("Text:", row['text'].split("\n", 1)[0])
print("Top 5 terms:")

scores = tf_idf[i]
indices = (-scores).argsort()

for j in indices[:5]:
  print(idx2word[j])

Label: business
Text: China keeps tight rein on credit
Top 5 terms:
china
breakneck
credit
%
rapid


In [66]:
row = df.iloc[i]
for elem in ['China', 'breakneck', 'credit', '%', 'rapid']:
    print(elem in row['text'])

True
True
True
True
True


In [58]:
row['text']

'Athens memories soar above lows\n\nWell, it\'s goodbye to another Olympic year and as usual there were plenty of highs and lows in Athens.\n\nObviously, there\'s no getting away from the differing fortunes of Kelly Holmes and Paula Radcliffe. But I want to remind you of a few more events that made 2004 another year to remember - or forget - for athletics. \n\n \n\nOne of my favourite Olympic moments was Kelly\'s success in the 800m.\n\nWinning that race was the key to her success because if she won that then the 1500m would be a bit of a formality. Kelly had been full of "should I, shouldn\'t I?" thoughts about going for the double in Athens. I thought why wouldn\'t you do the 800m, it\'s your best event? It was such good fun to commentate on her 1500m and it was nice to be able to be part of her Athens story. \n\n \n\nThe victory for the British men\'s 4x100m relay team was a bit of a surprise but a great climax to the Games. I think the four of them - Jason Gardener, Darren Campbell

In [67]:
import gensim

ModuleNotFoundError: No module named 'gensim'

In [78]:
import gensim
from gensim.models import Word2Vec

# przygotowanie zbioru tekstów
sentences = [["this", "is", "the", "first", "sentence", "for", "word2vec"],
             ["this", "is", "the", "second", "sentence"],
             ["yet", "another", "sentence"],
             ["one", "more", "sentence"],
             ["and", "the", "final", "sentence"]]

# trenowanie modelu Word2Vec
model = Word2Vec(sentences, min_count=1)

# wyświetlenie wektora reprezentującego słowo "sentence"

In [79]:
model.wv.key_to_index

{'sentence': 0,
 'the': 1,
 'is': 2,
 'this': 3,
 'final': 4,
 'and': 5,
 'more': 6,
 'one': 7,
 'another': 8,
 'yet': 9,
 'second': 10,
 'word2vec': 11,
 'for': 12,
 'first': 13}

In [81]:
model.wv.get_vector('dupa')

KeyError: "Key 'dupa' not present"